name: Create Test Issue

on:
  project_card:
    types: [moved]

jobs:
  create-test-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Test Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const card = context.payload.project_card;
            
            const column = await github.rest.projects.getColumn({
              column_id: card.column_id
            });
            
            if (column.data.name !== 'Need to add in On-Demand/Validation Checks') {
              console.log(`Card not in target column. Current: ${column.data.name}`);
              return;
            }
            
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'test',
              body: 'This is a test issue created automatically.',
              labels: ['auto-created']
            });
            
            console.log(`Created test issue #${newIssue.data.number}`);
            
            const project = await github.rest.projects.getProject({
              project_id: column.data.project_id
            });
            
            const columns = await github.rest.projects.listColumns({
              project_id: project.data.id
            });
            
            const todoColumn = columns.data.find(col => col.name === 'Todo');
            
            if (todoColumn) {
              await github.rest.projects.createCard({
                column_id: todoColumn.id,
                content_id: newIssue.data.id,
                content_type: 'Issue'
              });
              
              console.log(`Added issue to Todo column`);
            } else {
              console.log('Todo column not found');
            }