name: Create Test Issue

on:
  workflow_dispatch:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read

jobs:
  create-test-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Test Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const label = context.payload.label;
            
            // Trigger when a specific label is added
            if (label.name !== 'need-ondemand-validation') {
              console.log(`Not the target label. Added: ${label.name}`);
              return;
            }
            
            console.log(`Processing issue #${issue.number}: ${issue.title}`);
            
            // Create the test issue
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'test',
              body: `This is a test issue created automatically.

              Related to issue #${issue.number}: ${issue.title}`,
              labels: ['auto-created']
            });
            
            console.log(`Created test issue #${newIssue.data.number}`);