name: Create On Demand and Validity Checks Issue

on:
  workflow_dispatch:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read

jobs:
  create-on-demand-validity-checks-support-issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    
    steps:
      - name: Create On Demand and Validity Checks Issue 
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const label = context.payload.label;
            
            if (label.name !== 'Needs On Demand and Validity Checks') {
              return;
            }
            
            const tokenMatch = issue.title.match(/Add validator for\s+(.+)$/i);
            const tokenName = tokenMatch ? tokenMatch[1] : 'UNKNOWN_TOKEN';
            
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Enable On-Demand and Validity Checks for ${tokenName}`,
              body: `
              **Original Issue:** #${issue.number}
              **Token:** ${tokenName}

              ### Implementation Steps:
              - [ ] Edit \`config.go\` file to add:
                - [ ] \`WithOnDemandChecksSupportedForTokenTypes("${tokenName}")\`
                - [ ] \`WithValidityChecksSupportedForTokenTypes("${tokenName}")\`
                - [ ] Remove \`DisableValidityUpdatesForTokenTypes("${tokenName}")\` if present

              ### Files to Update:
              - \`ts/partnervalidation/validators/config/config.go\`

              **Auto-created from:** ${issue.title}`,
                            labels: ['auto-created', 'on-demand-validation']
                          });
              
                          
                        